FROM ruby:3.2 as rails-app-creator

# Default directory
ENV INSTALL_PATH /rails-app
RUN mkdir -p $INSTALL_PATH

# Ensure gems are installed on a persistent volume and available as bins
VOLUME /bundle
RUN bundle config set --global path '/bundle'
ENV PATH="/bundle/ruby/3.2.0/bin:${PATH}"

# Install rails
RUN gem install rails bundler
WORKDIR /rails-app

# Run a shell
CMD ["/bin/sh"]